services:
  - type: web
    name: python-edition-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_curriculum_data && python manage.py ensure_superuser --noinput
    startCommand: gunicorn python_edition_django.wsgi
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
