version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: python_edition
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/python_edition_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python /app/manage.py runserver 0.0.0.0:8000
volumes:
  db_data:
