# Generated by Django 5.2.8 on 2026-03-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_created_at_quizattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('score', models.FloatField()),
                ('passed_tests', models.IntegerField()),
                ('total_tests', models.IntegerField()),
                ('attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'lesson'], name='user_progre_user_id_2463b9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'topic'], name='user_progre_user_id_ca5af0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='user_progre_user_id_2c0065_idx'),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['user', 'challenge'], name='core_usersu_user_id_ff8178_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['user', 'topic'], name='core_usersu_user_id_90f34f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['user', 'created_at'], name='core_usersu_user_id_77a629_idx'),
        ),
    ]
